name: biosense
description: BioSense v1.0 — Early Homeostasis Deviation Alert | ALTEA-GARAY HTS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado
  provider: ^6.1.2

  # Internacionalización
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Persistencia local
  shared_preferences: ^2.2.3

  # PDF para médico
  pdf: ^3.10.8
  printing: ^5.12.0

  # QR
  qr_flutter: ^4.1.0

  # Seguridad tokens
  crypto: ^3.0.5

  # Notificaciones locales
  flutter_local_notifications: ^17.2.4

  # Íconos
  cupertino_icons: ^1.0.6

  # BLE — versión fija comprobada
  flutter_blue_plus: 1.14.0

  # Voz
  flutter_tts: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/images/
